name: Test SVG Parsing

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

# permissions:
#   contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - run: |
        python -m pip install --upgrade pip
        # opencv only used for testing
        pip install pytest opencv-python
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - run: python3 -m pytest -v tests
